apiVersion: apps/v1 # versão do Deployment
kind: Deployment # tipo de arquivo yaml
metadata: 
  name: app-deployment # nome do arquivo POD
  labels: # rótulo de identificação
    app: app
    env: production
  namespace: default # namespace default (pode ser colocado outro, mas é necessário criar antes de executar este arquivo yaml)

spec:
  selector:
    matchLabels: # verifica o rótulo de identificação do metadata
      app: app
  template:
    metadata:
      name: pod-app # nome do metadata
      labels: # verifica o rótulo de identificação com o selector do spec
        app: app
        env: production
    spec: # especificação dos dados do container
      containers:
        - name: nginx-container # nome do container
          image: nginx # nome da imagem a ser usada
          ports:
            - containerPort: 80 # porta que vai rodar no POD
              name: app-target # tag usada para permitir a comunicação com o "targetPort" do Service
  replicas: 1 # número de replicas

---

apiVersion: v1 # versão do Service
kind: Service # tipo de arquivo yaml
metadata:
  name: app-service # nome do arquivo Service
spec:
  type: ClusterIP # tipo de service - (comunicação interna)
  selector: # comunicação com o Deployment
    app: app
  ports:
    - name: app-port # nome do ports
      protocol: TCP # tipo de protocolo de comunicação
      port: 80 # porta que o Service está disponibilizado
      targetPort: app-target # porta que o serviço tem como alvo em qualquer POD (aqui ele faz uma ligação com o "ports" do Deployment)